### ISSUE TITLE
SyntaxError: 'utf8' codec can't decode byte 0x8a in position 0: invalid start byte

### ISSUE THREAD

**Issue by dagwieers** [jaylinski/kodi-addon-vimeo#37]
Starting de Vimeo add-on after installation fails with:
```
2020-07-10 11:00:34.037 T:1224725376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: 'utf8' codec can't decode byte 0x8a in position 0: invalid start byte (message.py, line 3)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vimeo/addon.py", line 1, in <module>
                                                from resources import plugin
                                              File "/storage/.kodi/addons/plugin.video.vimeo/resources/plugin.py", line 3, in <module>
                                                standard_library.install_aliases()  # noqa: E402
                                              File "/storage/.kodi/addons/script.module.future/libs/future/standard_library/__init__.py", line 478, in install_aliases
                                                from future.backports.urllib import request
                                              File "/storage/.kodi/addons/script.module.future/libs/future/backports/urllib/request.py", line 97, in <module>
                                                from future.backports.http import client as http_client
                                              File "/storage/.kodi/addons/script.module.future/libs/future/backports/http/client.py", line 76, in <module>
                                                from future.backports.email import parser as email_parser
                                              File "/storage/.kodi/addons/script.module.future/libs/future/backports/email/parser.py", line 15, in <module>
                                                from future.backports.email.feedparser import FeedParser, BytesFeedParser
                                              File "/storage/.kodi/addons/script.module.future/libs/future/backports/email/feedparser.py", line 32, in <module>
                                                from future.backports.email import message
                                              File "/storage/.kodi/addons/script.module.future/libs/future/backports/email/message.py", line 3
                                            SyntaxError: 'utf8' codec can't decode byte 0x8a in position 0: invalid start byte
                                            -->End of Python script error report<--
```

This is on a Kodi v18.7 running LibreELEC v9.2.3 on a Raspberry Pi 3B.

**Comment by dagwieers** [comment]
I assume the required **script.module.future** no longer supports Python 2?

**Comment by dagwieers** [comment]
Is the future library really necessary to get PY2/PY3 compatibility? We have been able to avoid it in our add-ons by enabling `unicode_literals` in Python 2.7 (and just a handful of wrappers).

You don't even need to check for PY2 explicitly, you can test for the availability of something, and provide a compatible alternative.

**Comment by jaylinski** [comment]
Hi! I'm using the future library to alias `urllib.parse`:
* https://python-future.org/compatible_idioms.html#urllib-module
* https://github.com/jaylinski/kodi-addon-vimeo/blob/v5.1.4/resources/plugin.py#L7

And yes, it can probably be avoided if `urllib.parse` is imported like you are doing here:
https://github.com/add-ons/plugin.video.vrt.nu/blob/v2.3.5/resources/lib/addon.py#L8-L11

I'm just wondering why you are getting this error in the first place...

**Comment by dagwieers** [comment]
I think the reason for this is because the future library uses `unicode_literals` whereas your add-on does not.

**Comment by dagwieers** [comment]
Reinstalling the future module fixes this. Not sure when this happened as the module was installed by another add-on (Catchup TV and more) which IIRC worked fine on this system before. Maybe an update since and a hardware issue caused this. :-/

**Comment by dagwieers** [comment]
I would still be interested to get rid of the dependency on the future library at some point, would a PR doing this be accepted?

**Comment by dagwieers** [comment]
We also have quite some experience with doing sanity and integration tests using GitHub CI.
→ https://github.com/add-ons/best-practices/wiki/Automated-testing
→ https://github.com/add-ons/plugin.video.vrt.nu/runs/838964367?check_suite_focus=true
Would a PR adding those be accepted?

**Comment by jaylinski** [comment]
@dagwieers Yes, a PR removing the `futures` dependency would be accepted (and appreciated). But please be aware that I will kick out any Python 2 compatibility stuff soon(ish) anyway: #22 (I will keep a branch for older Kodi versions)

Regarding GitHub-CI: I'm pretty happy with the TravisCI tests right now, so I'll keep them. But thanks for the tip, those GitHub-CI workflows look nice.

**Comment by dagwieers** [comment]
@jaylinski Why would you do this now? I would at least wait until Matrix has been released and a large user base has already moved to it. The Python 2 support has not been a real setback for our development. So the longer we have a single branch the easier it is to support all our users.

**Comment by jaylinski** [comment]
> @jaylinski Why would you do this now? I would at least wait until Matrix has been released and a large user base has already moved to it. The Python 2 support has not been a real setback for our development. So the longer we have a single branch the easier it is to support all our users.

I'm not doing it now, I'm waiting for the first Matrix beta release. I hate supporting an EOL software (like Python 2), that's why I want to get rid of it as soon as possible. But as I said, I'll keep a Python 2 compatible branch (which will only get bugfixes, so I don't worry about support too much).

**Comment by dagwieers** [comment]
I fully understand that supporting Python 2 while it is EOL is not something we would prefer, but if the majority of users are still, and will be running Python 2 for the foreseeable future. Python 3 support for us atm has a somewhat lower priority (we do have automated testing for all code-paths) simply because the users running Matrix today (and during beta) will be our first testers.

So we keep a single branch as long as possible, until Python 2 users fade out. Just because supporting both is almost no work, even for new functionality.

**Comment by dagwieers** [comment]
I just checked our own add-on's usage statistics and noticed we have 10x more Krypton users today than Matrix users ;-)
And 58x more Leia users than Matrix users.

http://mirrors.kodi.tv/stats?downloadstats&filter=plugin.video.vrt.nu-2.3.5

For Vimeo you have to compare downloads from v5.1.1 (Matrix) to v5.1.4 (Krypton and Leia):
- Krypton: 229k
- Leia: 443k
- Matrix: 1.2k

http://mirrors.kodi.tv/stats?downloadstats&filter=plugin.video.vimeo-5.1
