### ISSUE TITLE
Livestreams don't play

### ISSUE THREAD

**Issue by fkloft** [jaylinski/kodi-addon-vimeo#40]
I noticed the plugin crash when trying to play the recording of a finished livestream; the logs says "Api JSON seems to be invalid".

Debugging showed the "type" slot of the result object was `"live"`, not `"video"`, so I changed [this line](https://github.com/jaylinski/kodi-addon-vimeo/blob/master/resources/lib/vimeo/api.py#L175) from
```python3
if "type" in json_obj and json_obj["type"] == "video":
```
to:
```python3
if "type" in json_obj and json_obj["type"] in ("video", "live"):
```

This fixed the issue for me; I can play both ongoing livestreams as well as recordings of past streams.

**Comment by jaylinski** [comment]
Will be released in v5.2.0.

**Comment by fabrees** [comment]
Hello, this is the second time that I encountered that playing a live stream is not possible. After searching for a while I found this issue. When will 5.2.0 be released? Maybe I can save the effort of building the development build. Thanks!

**Comment by jaylinski** [comment]
@fabrees I'll try to finish the remaining v5.2.0 milestones tomorrow and will release a new version afterwards.
