### ISSUE TITLE
Support password protected live streams

### ISSUE THREAD

**Issue by lews-therin** [jaylinski/kodi-addon-vimeo#45]

**Comment by aqzina** [comment]
it could be related to this maybe? https://github.com/jaylinski/kodi-addon-vimeo/issues/43

**Comment by jaylinski** [comment]
Yes, definitely related.

Do you have a password protected video I can test with? That would be great for debugging!

**Comment by aqzina** [comment]
unfortunately i was sent this stream and they deleted it after the event :/ will let you know if i come across another one later..
