### ISSUE TITLE
Can someone migrate 2 addons?

### ISSUE THREAD

**Issue by zoreu** [jaylinski/kodi-addon-vimeo#59]
I need F4mproxy and f4mtester in python 3 and compatible with kodi 19+
https://mega.nz/folder/Xpx1mSzb#zMUUtAJC0wqhASkWu1_MKw

**Comment by jaylinski** [comment]
Does this have anything to do with the Vimeo addon?

If not, a better place to ask for this would probably be the forum: https://forum.kodi.tv/forumdisplay.php?fid=154
