### ISSUE TITLE
Proposal to fix "Login to vimeo fails"

### ISSUE THREAD

**Issue by purewasa** [jaylinski/kodi-addon-vimeo#62]
Hi jaylinski,

I installed the vimeo addon version 5.2.0 in kodi 18.4. I wanted to login to vimeo, because I have purchased videos on my personal account there. But it failed to show the OK dialogbox.
kodi.log notified an exception that unicode characters could not be translated with the ascii encoder in resources/plugin.py line 179.
This is due to the fact that in line 177 in 5.2.0 (l'ine3="{}\n{}".format('...) the template string gets filled with localized strings which contain unicode characters.
I finally fixed it by making the template string unicode as well ('line3=u"{}\n{}".format('...). Then I could successfully activate your addon to use my account and watch my purchased video.

So, I suggest you to make the template string in the master branch unicode the same way at the position: 
 https://github.com/jaylinski/kodi-addon-vimeo/blob/cabfd32897034dd203ece7bd36727fcab0391338/resources/plugin.py#L170-L174

because I guess, it will fail, as well!

Yours, sincerely

purewasa

**Comment by purewasa** [comment]
I have forgotton to mention how to reproduce this bug:
I used the german language which contains an O umlaut ('Ö') in 'Öffne', which is non-ASCII.
Just clicking on the 'Anmelden' ('login') item in the list and the error occurs.

**Comment by jaylinski** [comment]
@purewasa The `master`-branch is Python 3 only, which means you won't have this issue with Kodi v19.

If you can't update, I can fix the issue in the `krypton`-branch.

**Comment by purewasa** [comment]
@jaylinski Thanks for your offer. But for me, I am fine with my already fixed version 5.2.0. It has everything I need, at the moment. I don't think I will update it. If I update at all then I would take kodi 19.
