### ISSUE TITLE
xbmc.translatePath Error on kodi 19/20

### ISSUE THREAD

**Issue by Isayso** [jaylinski/kodi-addon-vimeo#63]
I guess there was something with xbmc.translatePath to xbmcvfs.translatePath for Python 3

Thanks

**Comment by jaylinski** [comment]
@Isayso Please provide the following information:

* Your Kodi version
* Your operation system
* Your Vimeo addon version

**Comment by Isayso** [comment]
I apologize for the missing information.
It's 6.0.0 on Kodi 19/20 (Libreelec 10/11) RPI3+

Thanks

**Comment by jaylinski** [comment]
I think I found the issue: `translatePath` has to be called via `xbmcvfs` now: https://github.com/xbmc/xbmc/pull/18345

I'll release a fixed version soon.

(Reminder: also fix this in the other plugins!)

**Comment by jaylinski** [comment]
@Isayso I published version 6.0.1, does it work for you now?

**Comment by Isayso** [comment]
Works partially. The videos from "trending" do not load. When I send links with http its okay.

**Comment by jaylinski** [comment]
@Isayso Can you give me one of the video-titles were HLS doesn't work? I'll look into it.

**Comment by Isayso** [comment]
https://vimeo.com/676996460
there were some more, but must reboot now, do not stop to try loading
