### ISSUE TITLE
embed.vhx.tv URLs

### ISSUE THREAD

**Issue by 89z** [jaylinski/kodi-addon-vimeo#67]
is this addon able to support these type URLs:

https://embed.vhx.tv/subscriptions/28599?vimeo=1
https://embed.vhx.tv/videos/1264265?vimeo=1

**Comment by jaylinski** [comment]
When sharing/playing Vimeo videos with this plugin, it can to be done via Vimeo-ID in the following format:

```
plugin://plugin.video.vimeo/play/?[video_id]
```

The URLs you are linking contain domain-protected videos, which can't be played with this plugin (yet). See https://github.com/jaylinski/kodi-addon-vimeo/issues/46.
